name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH for deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy project to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r ./* ubuntu@16.171.159.192:/home/ubuntu/app-test/

      - name: Execute deployment script
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@16.171.159.192 "bash /home/ubuntu/app-test/deploy.sh"
