name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH for deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known_hosts
        run: ssh-keyscan -H 16.171.159.192 >> ~/.ssh/known_hosts

      - name: Test SSH connection
        run: ssh -i ~/.ssh/id_rsa ubuntu@16.171.159.192 "echo 'Connexion SSH réussie'"

      - name: Copy project to EC2
        run: scp -o StrictHostKeyChecking=no -r $(git ls-files) ubuntu@16.171.159.192:/home/ubuntu/app-test/

      - name: Execute deployment script
        run: ssh -i ~/.ssh/id_rsa ubuntu@16.171.159.192 "bash /home/ubuntu/app-test/deploy.sh"
